name: "Build"
on:
  push:
    branches:
      - '**'
jobs:
  build-all:
    name: "Build ${{ matrix.tool }}: ${{ matrix.project }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ant
          - tool: "ant"
            project: "java-basic"
          # Bazel
          - tool: "bazel"
            project: "java-basic"
          # bld
          - tool: "bld"
            project: "java-basic"
          # Gradle
          - tool: "gradle"
            project: "java-basic"
          - tool: "gradle"
            project: "kotlin-basic"
          # Kotlin Toolchain
          - tool: "kotlin-toolchain"
            project: "java-basic"
          - tool: "kotlin-toolchain"
            project: "kotlin-basic"
          # Maven
          - tool: "maven"
            project: "java-basic"
          # Mill
          - tool: "mill"
            project: "java-basic"
          # sbt
          - tool: "sbt"
            project: "java-basic"
    defaults:
      run:
        working-directory: ./${{ matrix.tool }}/${{ matrix.project }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Ant
        if: ${{ matrix.tool == 'ant' }}
        uses: cedx/SetupAnt@v6
        with:
          version: =1.10.17

      - name: Setup Bazel
        if: ${{ matrix.tool == 'bazel' }}
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Setup Gradle
        if: ${{ matrix.tool == 'gradle' }}
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic

      - name: Setup sbt
        if: ${{ matrix.tool == 'sbt' }}
        uses: sbt/setup-sbt@v1

      - name: Extract scripts
        id: extract
        working-directory: ./${{ matrix.tool }}
        run: |
          extract_block() {
            local label="$1"
            local output_name="$2"
            {
              echo "${output_name}<<EOF"
              awk -v label="$label" '
              $0==label { found=1; next }
              found && /^```/ {
              if (!inblock) { inblock=1; next }
              else exit
            }
            found && inblock { print }
            ' "README.md"
            echo "EOF"
            } >> "$GITHUB_OUTPUT"
          }
          extract_block "Building app:" compile_script
          extract_block "Running app:" run_script
          extract_block "Testing app:" test_script

      - name: Compile project
        run: ${{ steps.extract.outputs.compile_script }}

      - name: Verify program
        run: |
          OUTPUT=$(${{ steps.extract.outputs.run_script }})
          echo "$OUTPUT"
          
          if echo "$OUTPUT" | grep -q "Here goes the joke:"; then
            exit 0
          else
            exit 1
          fi

      - name: Test project
        run: ${{ steps.extract.outputs.test_script }}
