name: "Build"
on:
  push:
    branches:
      - '**'
jobs:
  build-gradle:
    name: "Build Gradle"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gradle
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Build project
        run: ./gradlew assemble

      - name: Verify program
        run: |
          OUTPUT=$(./gradlew run)
          echo "$OUTPUT"
  
          if echo "$OUTPUT" | grep -q "Here goes the joke:"; then
            exit 0
          else
            exit 1
          fi

      - name: Test project
        run: ./gradlew test

  build-bazel:
    name: "Build Bazel"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bazel
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Build project
        run: bazel build //:JokeApp

      - name: Verify program
        run: |
          OUTPUT=$(bazel run //:JokeApp)
          echo "$OUTPUT"
          
          if echo "$OUTPUT" | grep -q "Here goes the joke:"; then
            exit 0
          else
            exit 1
          fi

      - name: Test project
        run: bazel test //:JokeAppTest
